<style>
td.input {
    width: 500px;
    color: #000000;
    background-color: #FAFAEF;
    font-weight: normal;
    border: 1px solid #EAEAEA;
}
td label {
    width: 100px;
    color: #000000;
    text-transform: uppercase;
    font-weight: normal;
    font-size: .9em;
}
</style>
<div id="part-tabs">
    <ul>
        <li><a href="#tabs-1">Part Detail</a></li>
        <li><a href="#tabs-2">Attributes</a></li>
    </ul>
    <div id="tabs-1">
    <?php 
        if ($this->part->hasEmptyAttributes()) {
            echo '<div class="ui-state-error ui-corner-all" style="padding: 5px; text-align: center; font-weight: bold;">This part contains attributes that have no value.</div>';
        }
        echo $this->form;
    ?>
    </div>
    <div id="tabs-2">
        <p>Click the Category Name to view the values associated each attribute associated with each Category.</p>
        <div id="attribute-accordion">
            <?php $dbParts = new Application_Model_DbTable_Parts(); 
            foreach ($this->categories as $category) {
                if ($category->hasAttributes()) {
                    printf('<h3><a href="#">%s</a></h3><div><table cellpadding="3" cellspacing="2">', $category->getLabel());

                    $attributes = $category->getAttributes();
                    foreach ($attributes as $attribute) {
                        $values = $attribute->getPartValues($this->part->id);
                        printf('<tr valign="top"><td width="150"><label>%s:</label></td><td class="input">', $attribute->name);

                        if ($attribute->attribute_type_id == 1 && $values) {
                        	// list of parts
                        	foreach ($values as $value) {
                                $part = $value->getPart();
                                printf('<li>%s - %s</li>', $part->part_id, $part->description);
                            }
                        } elseif ($attribute->attribute_type_id == 2 && $values) {
                        	// list of mappings
                        	foreach ($values as $value) {
                        		// first extract the part id and the value
                        		$tempString = substr(trim($value->value), 1, strlen(trim($value->value)) - 2);
                        		$valueArray = explode(",", $tempString);
                                $part = $dbParts->getPart(trim($valueArray[0]));
                                printf('<li>%s - %s (Value: %s)</li>', $part->part_id, $part->description, trim($valueArray[1]));
                            }    
                        } else {
                        	if ($values)
                            	echo $values[0]->value;	
                        }
                    }
                    echo '</td></tr>';
                    echo '</table></div>';
                }
            }?>

        </div>
    </div>
</div>
