<div id="page-content">
<h1>Thank You</h1>
<p>Your account has been created. You will receive a follow up email shortly with information you will need in order to log in for the first time.</p>

<h1>Contact</h1>
<p>Contact us by email at <?php echo Zend_Registry::get('config')->email->from_address."@".Zend_Registry::get('config')->email->domain; ?>. Phone: <?php echo Zend_Registry::get('config')->website->phone; ?>.</p>
</div>
<!-- Google Code for Registration Conversion Page -->
<!-- script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1014284451;
var google_conversion_language = "en";
var google_conversion_format = "1";
var google_conversion_color = "ffffff";
var google_conversion_label = "du8fCNXJzAMQo4HT4wM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript"  
src="http://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt=""  
src="http://www.googleadservices.com/pagead/conversion/1014284451/?label=du8fCNXJzAMQo4HT4wM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>  -->
