Dear <?php echo trim($this->first_name . ' ' .$this->last_name); ?>,

Thank you for your interest in GenoCAD. We have created your account. 

----------------------------
I. Manage your account
----------------------------

Please use the username and password listed below to log into your account for the first time.
 
Username: <?php echo $this->login; ?>

Password: <?php echo $this->password; ?>

You can login by navigating to this link: <?php echo Zend_Registry::get('config')->website->domain_name;?>

Once you are logged in, we strongly recommend that you click on the "My Profile" link to change your password.

----------------------------
II. Make the most of GenoCAD
----------------------------

The GenoCAD team has developed tutorials available on Figshare: http://dx.doi.org/10.6084/m9.figshare.153827

The tutorial is self-guided and comes with extensive notes. Investing an hour or two going through the tutorial will go a long way towards helping you make the most of GenoCAD.  

Should you need assistance at any point during the tutorial or while using GenoCAD, you can always reach us by clicking on the support link at the bottom of each page: <?php echo Zend_Registry::get('config')->website->domain_name;?>/index/support One of us will get back to you shortly.

We do not send emails to GenoCAD users except through our optional mailing list. In order to stay informed of GenoCAD's most recent developments, server maintenance, and other issues that may impact your use of GenoCAD, we strongly encourage you to join GenoCAD's low-volume mailing list by clicking on http://eepurl.com/G8qcT.

------------------------------------
III. Be part of the of the community
------------------------------------

GenoCAD is also present in several social media. We encourage you to follow GenoCAD in your social media of choice and be a part of broader conversations about GenoCAD and synthetic biology. 

LinkedIn: http://www.linkedin.com/groups/GenoCAD-User-Group-3934875
Twitter: http://twitter.com/genocad
Facebook: https://www.facebook.com/genocad


The GenoCAD team.
