<body>
<p>A new account was created on the <?php echo $this->site; ?> website:</p>
<p></p>
<p>Email:       <?php echo $this->user->login; ?></p>
<p>First Name:  <?php echo $this->user->first_name; ?></p>
<p>Last Name:   <?php echo $this->user->last_name; ?></p>
<p>Institution: <?php echo $this->user->institution; ?></p>
<p>Position:    <?php echo $this->user->position; ?></p>
<p>Country:     <?php echo $this->user->country; ?></p>
<p>Address:     <?php echo $this->user->address; ?></p>
<p>City:        <?php echo $this->user->city; ?></p>
<p>State/Province:  <?php echo $this->user->state; ?></p>
<p>Zip/Postal Code: <?php echo $this->user->zip; ?></p>
<p>Telephone:   <?php echo $this->user->telephone; ?></p>
<p>Website:     <?php echo $this->user->website; ?></p>
<p>Reason for Account:      <?php echo $this->user->why_ask_for_account; ?></p>
</body>