<div id="page-content">
<h1>What is GenoCAD&trade;?</h1>
<p>GenoCAD is an open-source computer-assisted-design (CAD) application for synthetic biology. The foundation of GenoCAD is to consider DNA as a language to program 
synthetic biological systems. GenoCAD includes a large database of annotated genetic parts which are the words of the language. GenoCAD also includes design rules 
describing how parts should be combined in genetic constructs. These rules are used to build a wizard that guides users through the process of designing complex 
genetic constructs and artificial gene networks. The same rules are used by the GenoCAD compiler to maintain the integrity of existing constructs. GenoCAD provides 
users with data import and export capabilities using standard formats (FASTA, GenBank, and tab-delimited text) so that users' personal workspaces can be customized to 
meet their specific needs. 
</p>
<h1>Getting started</h1>
<ul>
    <li>Step by step tutorial: <a href="<?php echo Zend_Registry::get('config')->website->domain_name.'/index/documents'; ?>">Documents</a></li>
    <li>Technical support: <a href="<?php echo Zend_Registry::get('config')->website->domain_name.'/index/support';?>">Support</a></li>
</ul>

<h1>Who develops GenoCAD?</h1>
<p>GenoCAD is developed by the <a target="new" href="http://www.peccoud.org">Peccoud Lab</a> at <a target="VBI" href="http://www.vbi.vt.edu">Virginia Bioinformatics Institute</a>. Up-to-date information 
about GenoCAD is available on the Peccoud Lab website at <a target="new" href="http://peccoud.vbi.vt.edu/?s=genocad">www.peccoud.org</a></p>
<p>This material is based upon work supported by the National Science
Foundation under Grant No. <a target="new" href="http://www.nsf.gov/awardsearch/showAward.do?AwardNumber=0850100">EF-0850100</a>. Any opinions, findings, and conclusions or
recommendations expressed in this material are those of the author(s)
and do not necessarily reflect the views of the National Science
Foundation.</p>

<h1>GenoCAD Source Code</h1>
<p>GenoCAD is distributed open source using the <a target="license" href="http://www.apache.org/licenses/LICENSE-2.0.html">Apache
Version 2.0 License</a>. This license has been approved by the <a target="osi" href="http://www.opensource.org/licenses/bsd-license.php">Open Source Initiative</a>.</p>
<p>The GenoCAD source code is hosted on SourceForge <a target="sourceforge" href="http://sourceforge.net/projects/genocad/develop">http://sourceforge.net/projects/genocad/develop</a>.</p>
 
</div>