<div id="page-content">
<h1>Tutorials</h1>
<ul>
	<li>
	<h4>Step by step tutorial. (Available from FigShare.com): <a href="http://figshare.com/articles/GenoCAD_Training_Set_I/153827"
		target="Tutorial">Tutorial</a></h4>
	<br>
	</li>
	<li>
	<h4>Introduction to GenoCAD Online Tutorial Suite. (Available from OpenHelix.com): <a href="http://www.openhelix.com/cgi/tutorialInfo.cgi?id=126"
		target="Intro to GenoCAD">Tutorial</a></h4>
	<br>
	</li>
	<li>
	<h4>GenoCAD Advanced Topics. (Available from OpenHelix.com): <a href="http://www.openhelix.com/cgi/tutorialInfo.cgi?id=127"
		target="GenoCAD Advanced Topics">Tutorial</a></h4>
	<br>
	</li>
</ul>
<h1>Sample Data</h1>
<ul><li>GenoCAD provides some public grammars on the website that can be copied into your own workspace within GenoCAD for learning the system and experimentation.</li></ul>
<ul><li>In addition, there are example grammars that may be downloaded from <a target="new" href="http://figshare.com/articles/search?q=genocad&quick=1&x=0&y=0">FigShare</a> and uploaded into your GenoCAD workspace.  These grammars include a Training Set grammar that is used in the Tutorial, as well as some legacy grammars that were used in publications.</li></ul>
<h1>References</h1>
<ul><li>Cai Y, Hartnett B, Gustafsson C, Peccoud J. (2007) A syntactic model to design and verify synthetic genetic constructs derived from standard biological parts. <a
		target="http://bioinformatics.oxfordjournals.org/cgi/content/short/btm446v2"
		href="http://bioinformatics.oxfordjournals.org/cgi/content/short/btm446v2">Bioinformatics
	23(20): 2760-2767</a>.
</li></ul><ul><li>Peccoud J, Blauvelt MF, Cai Y, Cooper KL, Crasta O, DeLalla EC,
	Evans C, Folkerts O, Lyons BM, Mane SP, Shelton R, Sweede MA, Waldon
	SA. (2008) Targeted development of registries of biological parts <a
		target="http://www.plosone.org/article/info:doi/10.1371/journal.pone.0002671"
		href="http://www.plosone.org/article/info%3Adoi/10.1371/journal.pone.0002671">PLoS
	ONE 3(7):e2671</a>.</li></ul><ul>
	<li>Cai Y, Lux MW, Adam L, Peccoud J. (2009) Modeling
	structure-function relationships in synthetic DNA sequences using
	attribute grammars <a
		target="http://www.ploscompbiol.org/article/info%3Adoi/10.1371/journal.pcbi.1000529"
		href="http://www.ploscompbiol.org/article/info%3Adoi/10.1371/journal.pcbi.1000529">PLoS
	Comput Biol 5(10):e1000529</a></li></ul><ul>
	<li>
Ball DA, Lux MW, Graef RR, Peterson MW, Valenti JD, Dileo J, Peccoud J (2010) Co-design in synthetic biology, a system-level analysis of the development of an environmental sensing device. <a target="http://www.ncbi.nlm.nih.gov/pubmed/19908391" href="http://www.ncbi.nlm.nih.gov/pubmed/19908391">Pac.Symp.Biocomput. 385-96</a>.
</li></ul>
<ul><li>Cai Y, Wilson ML, Peccoud J. (2010) GenoCAD for iGEM: a grammatical
	approach to the design of standard-compliant constructs <a
		target="http://nar.oxfordjournals.org/cgi/content/abstract/38/8/2637"
		href="http://nar.oxfordjournals.org/cgi/content/abstract/38/8/2637">Nucleic
	Acids Research 38, 2637-2644</a>.</li></ul>
	<ul><li>
Wilson ML, Hertzberg R, Adam L, Peccoud J. (2011) A step-by-step introduction to rule-based design of synthetic genetic constructs using GenoCAD. <a target="http://www.ncbi.nlm.nih.gov/pubmed/21601678" href="http://www.ncbi.nlm.nih.gov/pubmed/21601678">Methods in Enzymology 498:173-88
</a>.</li></ul>
<ul><li>
Lux MW, Bramlett BW, Ball DA, Peccoud J (2012) Genetic Design Automation: engineering fantasy or scientific renewal? <a target="http://www.cell.com/trends/biotechnology/abstract/S0167-7799(11)00163-6" href="http://www.cell.com/trends/biotechnology/abstract/S0167-7799(11)00163-6">Trends in Biotechnology 30:120-126</a>.
</li></ul>
<ul><li>
Wilson ML, Okumoto S, Adam L, Peccoud J (2013) Development of a domain-specific genetic language to design Chlamydomonas reinhardtii expression vectors <a target="http://bioinformatics.oxfordjournals.org/content/early/2013/12/06/bioinformatics.btt646" href="http://bioinformatics.oxfordjournals.org/content/early/2013/12/06/bioinformatics.btt646.full">Bioinformatics. doi:10.1093/bioinformatics/btt646</a>.
</li></ul>
<ul><li>
Purcell O, Peccoud J, & Lu TK (2013). Rule-Based Design of Synthetic Transcription Factors in Eukaryotes. <a target="http://pubs.acs.org/doi/full/10.1021/sb400134k" href="http://pubs.acs.org/doi/full/10.1021/sb400134k">ACS Synthetic Biology. doi:10.1021/sb400134k</a>.
</li></ul>
</div>
