<script>
$(document).ready(function() {
    $('#btn_parts, #btn_design, #btn_simulate').button();
});
</script>

<div style="position: relative; left: -1px; background: #B6B6B6 url(/template/images/background-home-channel.png) repeat-x top left;">

    <div class="home-tab" style="width:290px;">
        <div style="height: 100px; padding-top: 10px; "><img src="/images/other/parts.png"/></div>
        <div style="min-height: 100px;">
            <h3>Design Grammars and Build Parts Libraries</h3>
            <p style="padding: 10px;">Select or develop a rules-based grammar.  Create a library of parts, either by browsing the public parts or adding your own parts.</p>
        </div>
        <p style="text-align:center"><a id="btn_parts" href="/parts/">Browse Parts</a></p>
    </div>

    <div class="home-tab" style="width:300px;">
        <div style="height: 100px; padding-bottom: 10px;"><img src="/images/other/design.png"/></div>
        <div style="min-height: 100px;">
            <h3>Design a synthetic DNA molecule</h3>
            <p style="padding: 10px;">Choose a design strategy and a library of parts to work with.  Compose a design and save it.  You can also download its DNA sequence.</p>
        </div>
        <p style="text-align:center"><a id="btn_design" href="/design/">Design Construct</a></p>
    </div>

    <div class="home-tab" style="width:300px; border-right: none;">
        <div style="height: 100px; padding-top: 10px;"><img src="/images/other/simulate.png"/></div>
        <div style="min-height: 100px;">
            <h3>Simulate your construct</h3>
            <p style="padding: 10px;">Choose a function to study the behavior of your construct.</p>
        </div>
        <p style="text-align:center"><a id="btn_simulate" href="/simulate/">Simulate</a></p>
    </div>
    
    <div class="clear"></div>

</div>

<div class="shadow">&nbsp;</div>
<div class="clear">&nbsp;</div>

<div style="padding: 20px;">
    <h1>About GenoCAD
    <div style="float: right;">
    <!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style " addthis:url="http://www.genocad.org">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_button_google_plusone"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5115387b26c39860"></script>
<!-- AddThis Button END -->
    </div></h1>
    
    <p>
        GenoCAD is an open-source computer-assisted-design (CAD) application for synthetic biology. The foundation of GenoCAD is to consider DNA as a language to program synthetic biological systems. GenoCAD includes a large database of annotated genetic parts which are the words of the language. GenoCAD also includes design rules describing how parts should be combined in genetic constructs. These rules are used to build a wizard that guides users through the process of designing complex genetic constructs and artificial gene networks. The same rules are used by the GenoCAD compiler to maintain the integrity of existing constructs. GenoCAD provides users with data import and export capabilities using standard formats (FASTA, GenBank, and tab-delimited text) so that users' personal workspaces can be customized to meet their specific needs. 
    </p>
    <p style="text-align: right"><a href="/index/about/">Read More...</a></p>
</div>
