<div id="page-content">
<h1>TERMS OF USE AGREEMENT</h1>
<br/>
<p>Welcome to GenoCAD.  By using our website, you are agreeing to comply with and be bound by the following terms of use.  Please review the following terms carefully.  If you do not agree to these terms, you should not use this site.  </p>
<p>The term &#8220;Web Site&#8221; refers to <a href="<?php echo Zend_Registry::get('config')->website->domain_name; ?>"><?php echo Zend_Registry::get('config')->website->domain_name; ?></a>.  The term &#8220;Virginia Tech&#8221; refers to Virginia Polytechnic Institute and State University, the copyright owner of the Web Site.  The term &#8220;you&#8221; refers to the user or viewer of the Web Site.</p>
<h2>1. Acceptance of Agreement.</h2>
<p>You agree to the terms and conditions outlined in this Terms of Use Agreement (&#8220;Agreement&#8221;) with respect to use of the Web Site.  This Agreement may be amended at any time by Virginia Tech without specific notice to you.  The latest Agreement will be posted on the Web Site, and you should review this Agreement prior to using the Web Site.</p>
<h2>2. Web Site Content</h2>
<p>GenoCAD is composed of a web-based application and a database of biological parts to design genetic constructs.  The Web Site contains information from Virginia Tech as well as other contributors.  Including information or materials on the Web Site does not constitute a waiver of any party&#8217;s rights to their information and materials.</p>
<h2>3. Copyright.</h2>
<p>The organization, graphics, design, compilation, magnetic translation, digital conversion, and data bases related to the Web Site are protected by copyright.  The copying, redistribution, use or publication by you of any part of this Web Site is strictly prohibited except as allowed under this Agreement.  </p>
<h2>4. Permitted Use.</h2>
<p>You are granted the right to access and use the Web Site for noncommercial lawful purposes only.  You may access and the use the web site to retrieve information about biological parts, design synthetic DNA sequences combining multiple parts, or manage your own libraries of genetics parts.   The content of the Web Site is subject to change without notice. </p>
<p>The Web Site source code is distributed using the Apache v2.0 open source license. Commercial users of the Web Site are encouraged to take advantage of this licensing mechanism to run the application on their own server. </p>
<h2>5. DISCLAIMER OF WARRANTIES.</h2>
<p>NEITHER VIRGINIA TECH NOR ANY THIRD PARTIES PROVIDE ANY WARRANTY OR GUARANTEE AS TO THE ACCURACY, TIMELINESS, PERFORMANCE, COMPLETENESS OR SUITABILITY OF THE INFORMATION AND MATERIALS FOUND OR OFFERED ON THE WEB SITE FOR ANY PARTICULAR PURPOSE.  THE DATABASE, INFORMATION AND MATERIALS ARE PROVIDED &#8220;AS IS&#8221;.  YOU ACKNOWLEDGE THAT SUCH INFORMATION AND MATERIALS MAY CONTAIN INACCURACIES OR ERRORS.  YOU SPECIFICALLY ACKNOWLEDGE THAT IF YOU USE THE DATA ON THE WEB SITE FOR ANY PURPOSE , , VIRGINIA TECH AND THIRD PARTY CONTRIBUTORS OF THE DATA EXPRESSLY EXCLUDE ANY LIABILITY BASED ON ERRORS OR INACCURACIES IN THE DATA AND INFORMATION ON THE WEB SITE.  </p>
<h2>6. Limitation of Liability.</h2>
<p>In no event will Virginia Tech or other contributors to the Web Site be liable for any loss or damage, including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from use of this Web Site.</p>
<p>If you choose to use the  software on the Web Site to analyze your data or to contribute data to the Web Site for public use,  Virginia Tech assumes no responsibility for any use, misuse, publication, or loss of the data.  </p>
<h2>7. Termination.</h2>
<p>You agree that Virginia Tech, at its sole discretion, has the right to delete or deactivate your access to the Web Site, immediately and without notice, for any reason.  </p>
<h2>8. Links to Third-Party Web Sites.</h2>
<p>Links on the Web Site to third party web sites or information are provided solely as a convenience to you.  Such links do not constitute or imply an endorsement, sponsorship, or recommendation by Virginia Tech of the third party, the third-party web site, or the information contained therein.  If you use the links, you will leave the Web Site, and will be subject to the terms of use applicable to those web sites.</p>
<h2>9. Downloading files.</h2>
<p>Virginia Tech cannot and does not guarantee or warrant that files available for downloading through the Web Site will be free of infection by software viruses or other harmful computer code, files, or programs.</p>
<h2>10.  User Conduct</h2>
<p>You agree to use the Web Site only for lawful purposes.  You agree not to take any action that might compromise the security of the Web Site, render the Web site inaccessible to others or otherwise cause damage to the Web Site or the content thereof.  You agree not to use the Web Site in any manner that might interfere with the rights of third parties.  Virginia Tech may monitor your use of the Web Site and may restrict or prohibit use if your conduct is found to violate requirements of this section.</p>
<h2>11.  Enforcement/Choice of Law.</h2>
<p>If any part of this Agreement is determined to be invalid or unenforceable, it will not impact any other provision of this Agreement, all of which will remain in full force and effect.  Any and all disputes relating to this Agreement, your use of the Site, or the content are government by and will be interpreted in accordance with the laws of the Commonwealth of Virginia, without regard to any conflict of laws provisions.</p>
<p>&copy; 2009 Virginia Polytechnic Institute and State University.  All rights reserved.</p>
</div>